/**
 * Table whitelist and column metadata for generic reference data CRUD.
 * Only tables listed here can be accessed via the generic controller.
 */

export interface ColumnMeta {
  key: string;
  label: string;
  type: "string" | "number" | "boolean" | "date";
  required?: boolean;
  editable?: boolean;
  relation?: {
    table: string; // Key in REFERENCE_TABLES
    labelField: string; // Field to show as label
  };
  format?: "date" | "flag" | "select" | "boolean" | "enum";
  options?: Record<string, string>; // For enums
}

export interface TableConfig {
  tableName: string;
  label: string;
  hasIsActive: boolean;
  hasIsSystem: boolean;
  hasSortOrder: boolean;
  hasNameEn: boolean;
  permissionCode?: string;
  columns: ColumnMeta[];
}

export const REFERENCE_TABLES: Record<string, TableConfig> = {
  genders: {
    tableName: "genders",
    label: "Пол",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
    ],
  },
  age_groups: {
    tableName: "age_groups",
    label: "Возрастные группы",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "min_age", label: "Мин. возраст", type: "number", editable: true },
      { key: "max_age", label: "Макс. возраст", type: "number", editable: true },
    ],
  },
  languages: {
    tableName: "languages",
    label: "Языки",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name", label: "Название", type: "string", required: true, editable: true },
    ],
  },
  countries: {
    tableName: "countries",
    label: "Страны",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      {
        key: "code_alpha2",
        label: "Код Alpha-2",
        type: "string",
        required: true,
        editable: true,
        format: "flag",
      },
      { key: "code_alpha3", label: "Код Alpha-3", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "phone_code", label: "Тел. код", type: "string", editable: true },
      { key: "currency_code", label: "Валюта", type: "string", editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  federal_districts: {
    tableName: "federal_districts",
    label: "Федеральные округа",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      {
        key: "country_id",
        label: "Страна",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "countries", labelField: "name_ru" },
      },
    ],
  },
  region_types: {
    tableName: "region_types",
    label: "Типы регионов",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      {
        key: "country_id",
        label: "Страна",
        type: "number",
        editable: true,
        relation: { table: "countries", labelField: "name_ru" },
      },
    ],
  },
  olympic_categories: {
    tableName: "olympic_categories",
    label: "Олимпийские категории",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
    ],
  },
  sport_types: {
    tableName: "sport_types",
    label: "Типы спорта",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
    ],
  },
  organization_levels: {
    tableName: "organization_levels",
    label: "Уровни организаций",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: true,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  organization_types: {
    tableName: "organization_types",
    label: "Типы организаций",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: true,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "description", label: "Описание", type: "string", editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
    ],
  },
  competition_categories: {
    tableName: "competition_categories",
    label: "Категории соревнований",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "level", label: "Уровень (0-10)", type: "number", required: true, editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      {
        key: "country_id",
        label: "Страна",
        type: "number",
        editable: true,
        relation: { table: "countries", labelField: "name_ru" },
      },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  indicator_categories: {
    tableName: "indicator_categories",
    label: "Категории индикаторов",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: true,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название (RU)", type: "string", required: true, editable: true },
      { key: "name_en", label: "Название (EN)", type: "string", editable: true },
      { key: "description", label: "Описание", type: "string", editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  measurement_units: {
    tableName: "measurement_units",
    label: "Единицы измерения",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: false,
    hasNameEn: true,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название (RU)", type: "string", required: true, editable: true },
      { key: "name_en", label: "Название (EN)", type: "string", editable: true },
      { key: "short_name_ru", label: "Сокр. (RU)", type: "string", editable: true },
      { key: "short_name_en", label: "Сокр. (EN)", type: "string", editable: true },
      { key: "unit_type", label: "Тип", type: "string", required: true, editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  event_types: {
    tableName: "event_types",
    label: "Типы событий",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: true,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название (RU)", type: "string", required: true, editable: true },
      { key: "name_en", label: "Название (EN)", type: "string", editable: true },
      { key: "description", label: "Описание", type: "string", editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  event_levels: {
    tableName: "event_levels",
    label: "Уровни событий",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: true,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название (RU)", type: "string", required: true, editable: true },
      { key: "name_en", label: "Название (EN)", type: "string", editable: true },
      { key: "description", label: "Описание", type: "string", editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  event_stages: {
    tableName: "event_stages",
    label: "Этапы событий",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: true,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название (RU)", type: "string", required: true, editable: true },
      { key: "name_en", label: "Название (EN)", type: "string", editable: true },
      { key: "description", label: "Описание", type: "string", editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  data_source_categories: {
    tableName: "data_source_categories",
    label: "Категории источников",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: true,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "description", label: "Описание", type: "string", editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
    ],
  },
  data_sources: {
    tableName: "data_sources",
    label: "Источники данных",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "url", label: "URL", type: "string", editable: true },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  regions: {
    tableName: "regions",
    label: "Регионы",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      {
        key: "country_id",
        label: "Страна",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "countries", labelField: "name_ru" },
      },
      {
        key: "federal_district_id",
        label: "Фед. округ",
        type: "number",
        editable: true,
        relation: { table: "federal_districts", labelField: "name_ru" },
      },
      {
        key: "region_type_id",
        label: "Тип региона",
        type: "number",
        editable: true,
        relation: { table: "region_types", labelField: "name_ru" },
      },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  disciplines: {
    tableName: "disciplines",
    label: "Спортивные дисциплины",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      {
        key: "country_sport_id",
        label: "Вид спорта",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "sports", labelField: "name_ru" }, // Assuming it links to sports for simplicity in UI
      },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  referee_license_categories: {
    tableName: "referee_license_categories",
    label: "Категории лицензий персонала",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "short_name_ru", label: "Сокр. название", type: "string", editable: true },
      { key: "level", label: "Уровень (1-5)", type: "number", required: true, editable: true },
      {
        key: "sport_id",
        label: "Вид спорта",
        type: "number",
        editable: true,
        relation: { table: "sports", labelField: "name_ru" },
      },
      {
        key: "discipline_id",
        label: "Дисциплина",
        type: "number",
        editable: true,
        relation: { table: "disciplines", labelField: "name_ru" },
      },
      {
        key: "personnel_type",
        label: "Тип",
        type: "string",
        required: true,
        editable: true,
        format: "enum",
        options: {
          referee: "Судья",
          trainer: "Тренер",
          other: "Другое",
        },
      },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  region_population: {
    tableName: "region_population",
    label: "Население регионов",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      {
        key: "region_id",
        label: "Регион",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "regions", labelField: "name_ru" },
      },
      { key: "year", label: "Год", type: "number", required: true, editable: true },
      { key: "population", label: "Население", type: "number", required: true, editable: true },
      {
        key: "data_source_id",
        label: "Источник",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "data_sources", labelField: "name_ru" },
      },
    ],
  },
  venue_types: {
    tableName: "venue_types",
    label: "Типы спортивных объектов",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  sports_venues: {
    tableName: "sports_venues",
    label: "Спортивные объекты",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      {
        key: "venue_type_id",
        label: "Тип объекта",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "venue_types", labelField: "name_ru" },
      },
      {
        key: "region_id",
        label: "Регион",
        type: "number",
        editable: true,
        required: true,
        relation: { table: "regions", labelField: "name_ru" },
      },
      { key: "city", label: "Город", type: "string", editable: true },
      { key: "address", label: "Адрес", type: "string", editable: true },
      { key: "capacity", label: "Вместимость", type: "number", editable: true },
      { key: "surface_type", label: "Покрытие", type: "string", editable: true },
      { key: "indoor", label: "Крытый", type: "boolean", editable: true },
      {
        key: "sport_id",
        label: "Вид спорта",
        type: "number",
        editable: true,
        relation: { table: "sports", labelField: "name_ru" },
      },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  sports_ranks: {
    tableName: "sports_ranks",
    label: "Спортивные разряды и звания",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "short_name_ru", label: "Сокр. название", type: "string", editable: true },
      { key: "level", label: "Уровень (0-10)", type: "number", required: true, editable: true },
      {
        key: "rank_type",
        label: "Тип (rank, title)",
        type: "string",
        required: true,
        editable: true,
      },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  region_economics: {
    tableName: "region_economics",
    label: "Экономика регионов",
    hasIsActive: false,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      {
        key: "region_id",
        label: "Регион",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "regions", labelField: "name_ru" },
      },
      { key: "year", label: "Год", type: "number", required: true, editable: true },
      { key: "budget_total", label: "Бюджет общ.", type: "number", editable: true },
      { key: "budget_sports", label: "Бюджет спорт", type: "number", editable: true },
      { key: "avg_salary", label: "Ср. зарплата", type: "number", editable: true },
      { key: "grp", label: "ВРП", type: "number", editable: true },
    ],
  },
  training_program_types: {
    tableName: "training_program_types",
    label: "Типы программ подготовки",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: true,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "sort_order", label: "Порядок", type: "number", editable: true },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  sports: {
    tableName: "sports",
    label: "Виды спорта",
    hasIsActive: true,
    hasIsSystem: true,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      {
        key: "olympic_category_id",
        label: "Олимп. категория",
        type: "number",
        editable: true,
        relation: { table: "olympic_categories", labelField: "name_ru" },
      },
      {
        key: "sport_type_id",
        label: "Тип спорта",
        type: "number",
        editable: true,
        relation: { table: "sport_types", labelField: "name_ru" },
      },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  seasons: {
    tableName: "seasons",
    label: "Сезоны",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "season_year", label: "Год", type: "number", editable: true },
      {
        key: "season_type",
        label: "Тип",
        type: "string",
        editable: true,
        format: "enum",
        options: {
          cross_year: "Переходящий год",
          single_year: "Календарный год",
          calendar_year: "Календарный год",
        },
      },
      { key: "start_date", label: "Начало", type: "date", editable: true, format: "date" },
      { key: "end_date", label: "Конец", type: "date", editable: true, format: "date" },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
  organizations: {
    tableName: "organizations",
    label: "Организации",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "abbreviation_ru", label: "Сокр. название", type: "string", editable: true },
      {
        key: "type_id",
        label: "Тип",
        type: "number",
        editable: true,
        relation: { table: "organization_types", labelField: "name_ru" },
      },
      {
        key: "level_id",
        label: "Уровень",
        type: "number",
        editable: true,
        relation: { table: "organization_levels", labelField: "name_ru" },
      },
      {
        key: "region_id",
        label: "Регион",
        type: "number",
        editable: true,
        relation: { table: "regions", labelField: "name_ru" },
      },
      {
        key: "parent_id",
        label: "Головая орг.",
        type: "number",
        editable: true,
        relation: { table: "organizations", labelField: "name_ru" },
      },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  events: {
    tableName: "events_catalog",
    label: "События",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "code", label: "Код", type: "string", required: true, editable: true },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "short_name_ru", label: "Сокр. название", type: "string", editable: true },
      { key: "description", label: "Описание", type: "string", editable: true },
      {
        key: "event_type_id",
        label: "Тип",
        type: "number",
        editable: true,
        relation: { table: "event_types", labelField: "name_ru" },
      },
      {
        key: "level_id",
        label: "Уровень",
        type: "number",
        editable: true,
        relation: { table: "event_levels", labelField: "name_ru" },
      },
      {
        key: "stage_id",
        label: "Этап",
        type: "number",
        editable: true,
        relation: { table: "event_stages", labelField: "name_ru" },
      },
      {
        key: "organizer_id",
        label: "Организатор",
        type: "number",
        editable: true,
        relation: { table: "organizations", labelField: "name_ru" },
      },
      {
        key: "sport_id",
        label: "Вид спорта",
        type: "number",
        editable: true,
        relation: { table: "sports", labelField: "name_ru" },
      },
      { key: "is_active", label: "Активно", type: "boolean", editable: true },
    ],
  },
  federations: {
    tableName: "federations",
    label: "Федерации",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      { key: "name_ru", label: "Название", type: "string", required: true, editable: true },
      { key: "short_name_ru", label: "Сокр. название", type: "string", editable: true },
      {
        key: "sport_id",
        label: "Вид спорта",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "sports", labelField: "name_ru" },
      },
      {
        key: "country_id",
        label: "Страна",
        type: "number",
        editable: true,
        relation: { table: "countries", labelField: "name_ru" },
      },
      {
        key: "region_id",
        label: "Регион",
        type: "number",
        editable: true,
        relation: { table: "regions", labelField: "name_ru" },
      },
      { key: "is_active", label: "Активна", type: "boolean", editable: true },
    ],
  },
  country_sports: {
    tableName: "country_sports",
    label: "Виды спорта в странах",
    hasIsActive: true,
    hasIsSystem: false,
    hasSortOrder: false,
    hasNameEn: false,
    columns: [
      { key: "id", label: "ID", type: "number" },
      {
        key: "sport_id",
        label: "Вид спорта",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "sports", labelField: "name_ru" },
      },
      {
        key: "country_id",
        label: "Страна",
        type: "number",
        required: true,
        editable: true,
        relation: { table: "countries", labelField: "name_ru" },
      },
      { key: "registry_code", label: "Код реестра", type: "string", editable: true },
      { key: "is_active", label: "Активен", type: "boolean", editable: true },
    ],
  },
};

/**
 * Returns table config or undefined if not in whitelist.
 */
export function getTableConfig(tableKey: string): TableConfig | undefined {
  return REFERENCE_TABLES[tableKey];
}

/**
 * Returns all available table keys for the meta endpoint.
 */
export function getAllTableMeta(): Array<{ key: string; label: string }> {
  return Object.entries(REFERENCE_TABLES).map(([key, config]) => ({
    key,
    label: config.label,
  }));
}
